services:
  postgres:
    image: postgres:16-alpine
    container_name: ciclo-solicitud-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: pedidos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d pedidos"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
